// Copyright 2024 The OpenConfig Contributors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: v1/proto/gsii/gsii.proto

package gsii

import (
	gnmi "github.com/openconfig/gnmi/proto/gnmi"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PersistenceMode indicates the type of persistence that is requested
// of the server.
type SessionParameters_PersistenceMode int32

const (
	// INVALID indicates that the client did not specify a value for the
	// persistence mode.
	SessionParameters_INVALID_PERSISTENCE SessionParameters_PersistenceMode = 0
	// DELETE indicates that when the `Modify` RPC that is being used by
	// the client terminates, the server should remove all entries that
	// are associated with the client.
	SessionParameters_DELETE SessionParameters_PersistenceMode = 1
	// PRESERVE indicates that when the `Modify` RPC that is being used
	// by the client terminates, the server should continue to store and
	// use the entries that are associated with the client.
	SessionParameters_PRESERVE SessionParameters_PersistenceMode = 2
)

// Enum value maps for SessionParameters_PersistenceMode.
var (
	SessionParameters_PersistenceMode_name = map[int32]string{
		0: "INVALID_PERSISTENCE",
		1: "DELETE",
		2: "PRESERVE",
	}
	SessionParameters_PersistenceMode_value = map[string]int32{
		"INVALID_PERSISTENCE": 0,
		"DELETE":              1,
		"PRESERVE":            2,
	}
)

func (x SessionParameters_PersistenceMode) Enum() *SessionParameters_PersistenceMode {
	p := new(SessionParameters_PersistenceMode)
	*p = x
	return p
}

func (x SessionParameters_PersistenceMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionParameters_PersistenceMode) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_gsii_gsii_proto_enumTypes[0].Descriptor()
}

func (SessionParameters_PersistenceMode) Type() protoreflect.EnumType {
	return &file_v1_proto_gsii_gsii_proto_enumTypes[0]
}

func (x SessionParameters_PersistenceMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionParameters_PersistenceMode.Descriptor instead.
func (SessionParameters_PersistenceMode) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{2, 0}
}

// ClientRedundancy indicates the type of redundancy that is expected of the
// server. All clients that are connected for the same role must agree on the
// redundancy mode.
type SessionParameters_ClientRedundancy int32

const (
	SessionParameters_INVALID_REDUNDANCY SessionParameters_ClientRedundancy = 0 // The client did not set the redundancy mode.
	SessionParameters_ALL_PRIMARY        SessionParameters_ClientRedundancy = 1
	SessionParameters_SINGLE_PRIMARY     SessionParameters_ClientRedundancy = 2
)

// Enum value maps for SessionParameters_ClientRedundancy.
var (
	SessionParameters_ClientRedundancy_name = map[int32]string{
		0: "INVALID_REDUNDANCY",
		1: "ALL_PRIMARY",
		2: "SINGLE_PRIMARY",
	}
	SessionParameters_ClientRedundancy_value = map[string]int32{
		"INVALID_REDUNDANCY": 0,
		"ALL_PRIMARY":        1,
		"SINGLE_PRIMARY":     2,
	}
)

func (x SessionParameters_ClientRedundancy) Enum() *SessionParameters_ClientRedundancy {
	p := new(SessionParameters_ClientRedundancy)
	*p = x
	return p
}

func (x SessionParameters_ClientRedundancy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionParameters_ClientRedundancy) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_gsii_gsii_proto_enumTypes[1].Descriptor()
}

func (SessionParameters_ClientRedundancy) Type() protoreflect.EnumType {
	return &file_v1_proto_gsii_gsii_proto_enumTypes[1]
}

func (x SessionParameters_ClientRedundancy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionParameters_ClientRedundancy.Descriptor instead.
func (SessionParameters_ClientRedundancy) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{2, 1}
}

// Operation is the type of operation that should be applied on the device.
type Operation_OperationType int32

const (
	// INVALID indicates the client did not set the operation.
	Operation_INVALID Operation_OperationType = 0
	// ADD indicates the value is being added. ADDs for existing paths are
	// interpreted as a replace. ADD is an idempotent operation.
	Operation_ADD Operation_OperationType = 1
	// DELETE indicates that the value is being deleted. When a DELETE is
	// sent, the value within the dynamic store is removed, and the value
	// specified by persistent configuration storage is utilised.
	Operation_DELETE Operation_OperationType = 2
)

// Enum value maps for Operation_OperationType.
var (
	Operation_OperationType_name = map[int32]string{
		0: "INVALID",
		1: "ADD",
		2: "DELETE",
	}
	Operation_OperationType_value = map[string]int32{
		"INVALID": 0,
		"ADD":     1,
		"DELETE":  2,
	}
)

func (x Operation_OperationType) Enum() *Operation_OperationType {
	p := new(Operation_OperationType)
	*p = x
	return p
}

func (x Operation_OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Operation_OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_gsii_gsii_proto_enumTypes[2].Descriptor()
}

func (Operation_OperationType) Type() protoreflect.EnumType {
	return &file_v1_proto_gsii_gsii_proto_enumTypes[2]
}

func (x Operation_OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Operation_OperationType.Descriptor instead.
func (Operation_OperationType) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{4, 0}
}

type SessionParametersResult_Status int32

const (
	SessionParametersResult_INVALID SessionParametersResult_Status = 0 // The target did not set the field correctly.
	SessionParametersResult_OK      SessionParametersResult_Status = 1 // The target accepted the session parameters.
)

// Enum value maps for SessionParametersResult_Status.
var (
	SessionParametersResult_Status_name = map[int32]string{
		0: "INVALID",
		1: "OK",
	}
	SessionParametersResult_Status_value = map[string]int32{
		"INVALID": 0,
		"OK":      1,
	}
)

func (x SessionParametersResult_Status) Enum() *SessionParametersResult_Status {
	p := new(SessionParametersResult_Status)
	*p = x
	return p
}

func (x SessionParametersResult_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionParametersResult_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_proto_gsii_gsii_proto_enumTypes[3].Descriptor()
}

func (SessionParametersResult_Status) Type() protoreflect.EnumType {
	return &file_v1_proto_gsii_gsii_proto_enumTypes[3]
}

func (x SessionParametersResult_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionParametersResult_Status.Descriptor instead.
func (SessionParametersResult_Status) EnumDescriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{7, 0}
}

// ModifyRequest is sent by the client to the target to make a modification to
// dynamic configuration on the device.
type ModifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// params is specified once at the start of a session to indicate the details
	// of the mode that should be used for the session.
	Params *SessionParameters `protobuf:"bytes,1,opt,name=params,proto3" json:"params,omitempty"`
	// The new_election_id field is used in an input message to indicate that a
	// new election has occurred and update the server as to the latest election
	// ID. The server arbitrates based on the input election ID that is provided
	// on a per operation basis.
	//
	// The election ID is set specifically for the role that the client is
	// within.
	//
	// TODO(robjs): Determine whether we can use gnmi_ext.MasterArbitration here.
	NewElectionId *Uint128 `protobuf:"bytes,2,opt,name=new_election_id,json=newElectionId,proto3" json:"new_election_id,omitempty"`
	// The set of operations that are to be applied to the target.
	Op []*Operation `protobuf:"bytes,3,rep,name=op,proto3" json:"op,omitempty"`
}

func (x *ModifyRequest) Reset() {
	*x = ModifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_gsii_gsii_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyRequest) ProtoMessage() {}

func (x *ModifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_gsii_gsii_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyRequest.ProtoReflect.Descriptor instead.
func (*ModifyRequest) Descriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{0}
}

func (x *ModifyRequest) GetParams() *SessionParameters {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ModifyRequest) GetNewElectionId() *Uint128 {
	if x != nil {
		return x.NewElectionId
	}
	return nil
}

func (x *ModifyRequest) GetOp() []*Operation {
	if x != nil {
		return x.Op
	}
	return nil
}

// Uint128 stores a 128-bit unsigned integer.
type Uint128 struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The high 64-bits of the uint128.
	High uint64 `protobuf:"varint,1,opt,name=high,proto3" json:"high,omitempty"`
	// The low 64-bits of the uint128.
	Low uint64 `protobuf:"varint,2,opt,name=low,proto3" json:"low,omitempty"`
}

func (x *Uint128) Reset() {
	*x = Uint128{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_gsii_gsii_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Uint128) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Uint128) ProtoMessage() {}

func (x *Uint128) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_gsii_gsii_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Uint128.ProtoReflect.Descriptor instead.
func (*Uint128) Descriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{1}
}

func (x *Uint128) GetHigh() uint64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Uint128) GetLow() uint64 {
	if x != nil {
		return x.Low
	}
	return 0
}

type SessionParameters struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Persistence SessionParameters_PersistenceMode  `protobuf:"varint,1,opt,name=persistence,proto3,enum=gsii.v1.SessionParameters_PersistenceMode" json:"persistence,omitempty"`
	Redundancy  SessionParameters_ClientRedundancy `protobuf:"varint,2,opt,name=redundancy,proto3,enum=gsii.v1.SessionParameters_ClientRedundancy" json:"redundancy,omitempty"`
	// role indicates a group for which athe election ID is relevant to. This
	// allows for subsets of the schema to have separate clients that are
	// authoritative for the subset of the data tree. See gnmi_ext.proto and
	// https://github.com/openconfig/reference/blob/master/rpc/gnmi/gnmi-master-arbitration.md
	// for additional details.
	//
	// A client (i.e., individual RPC context) participates in exactly one role.
	// The role is immutable throughout the lifetime of the RPC. The role MUST
	// be set for a client.
	Role string `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	// client_details provides details that indicate the initial state of
	// a client.
	//
	// Types that are assignable to ClientDetails:
	//
	//	*SessionParameters_InitialElectionId
	//	*SessionParameters_ClientId
	ClientDetails isSessionParameters_ClientDetails `protobuf_oneof:"client_details"`
}

func (x *SessionParameters) Reset() {
	*x = SessionParameters{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_gsii_gsii_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionParameters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionParameters) ProtoMessage() {}

func (x *SessionParameters) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_gsii_gsii_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionParameters.ProtoReflect.Descriptor instead.
func (*SessionParameters) Descriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{2}
}

func (x *SessionParameters) GetPersistence() SessionParameters_PersistenceMode {
	if x != nil {
		return x.Persistence
	}
	return SessionParameters_INVALID_PERSISTENCE
}

func (x *SessionParameters) GetRedundancy() SessionParameters_ClientRedundancy {
	if x != nil {
		return x.Redundancy
	}
	return SessionParameters_INVALID_REDUNDANCY
}

func (x *SessionParameters) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (m *SessionParameters) GetClientDetails() isSessionParameters_ClientDetails {
	if m != nil {
		return m.ClientDetails
	}
	return nil
}

func (x *SessionParameters) GetInitialElectionId() *Uint128 {
	if x, ok := x.GetClientDetails().(*SessionParameters_InitialElectionId); ok {
		return x.InitialElectionId
	}
	return nil
}

func (x *SessionParameters) GetClientId() *Uint128 {
	if x, ok := x.GetClientDetails().(*SessionParameters_ClientId); ok {
		return x.ClientId
	}
	return nil
}

type isSessionParameters_ClientDetails interface {
	isSessionParameters_ClientDetails()
}

type SessionParameters_InitialElectionId struct {
	// initial_election_id provides the current election ID at the time
	// of connection.
	InitialElectionId *Uint128 `protobuf:"bytes,4,opt,name=initial_election_id,json=initialElectionId,proto3,oneof"`
}

type SessionParameters_ClientId struct {
	// client_id provides a stable identifier for this client to be used
	// in ALL_PRIMARY modes.
	ClientId *Uint128 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3,oneof"`
}

func (*SessionParameters_InitialElectionId) isSessionParameters_ClientDetails() {}

func (*SessionParameters_ClientId) isSessionParameters_ClientDetails() {}

// ElectionID is a <role, election ID> tuple.
type ElectionID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// role is the string that identifies the role for which the client
	// RPC is providing state.
	Role string `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	// election_id is the uint128 election ID.
	ElectionId *Uint128 `protobuf:"bytes,2,opt,name=election_id,json=electionId,proto3" json:"election_id,omitempty"`
}

func (x *ElectionID) Reset() {
	*x = ElectionID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_gsii_gsii_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ElectionID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElectionID) ProtoMessage() {}

func (x *ElectionID) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_gsii_gsii_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElectionID.ProtoReflect.Descriptor instead.
func (*ElectionID) Descriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{3}
}

func (x *ElectionID) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ElectionID) GetElectionId() *Uint128 {
	if x != nil {
		return x.ElectionId
	}
	return nil
}

// Operation is an individual operation that acts on a specific <path, value>
// on the device.
type Operation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op Operation_OperationType `protobuf:"varint,1,opt,name=op,proto3,enum=gsii.v1.Operation_OperationType" json:"op,omitempty"`
	// The gnmi Path being updated.
	Path *gnmi.Path `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	// The gnmi TypedValue encoding for a value that is being set.
	Value *gnmi.TypedValue `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Operation) Reset() {
	*x = Operation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_gsii_gsii_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_gsii_gsii_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{4}
}

func (x *Operation) GetOp() Operation_OperationType {
	if x != nil {
		return x.Op
	}
	return Operation_INVALID
}

func (x *Operation) GetPath() *gnmi.Path {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *Operation) GetValue() *gnmi.TypedValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// ModifyResponse is sent from the target to the client in response to a
// ModifyRequest.
type ModifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Result:
	//
	//	*ModifyResponse_SessionParamsResult
	//	*ModifyResponse_LatestElectionId
	Result  isModifyResponse_Result `protobuf_oneof:"result"`
	Results []*OpResult             `protobuf:"bytes,3,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *ModifyResponse) Reset() {
	*x = ModifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_gsii_gsii_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ModifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifyResponse) ProtoMessage() {}

func (x *ModifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_gsii_gsii_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifyResponse.ProtoReflect.Descriptor instead.
func (*ModifyResponse) Descriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{5}
}

func (m *ModifyResponse) GetResult() isModifyResponse_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (x *ModifyResponse) GetSessionParamsResult() *SessionParametersResult {
	if x, ok := x.GetResult().(*ModifyResponse_SessionParamsResult); ok {
		return x.SessionParamsResult
	}
	return nil
}

func (x *ModifyResponse) GetLatestElectionId() *ElectionID {
	if x, ok := x.GetResult().(*ModifyResponse_LatestElectionId); ok {
		return x.LatestElectionId
	}
	return nil
}

func (x *ModifyResponse) GetResults() []*OpResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type isModifyResponse_Result interface {
	isModifyResponse_Result()
}

type ModifyResponse_SessionParamsResult struct {
	// SessionParametersResult is sent as the first response on a particular
	// RPC to indicate the target's response to the client's requested
	// parameters.
	SessionParamsResult *SessionParametersResult `protobuf:"bytes,1,opt,name=session_params_result,json=sessionParamsResult,proto3,oneof"`
}

type ModifyResponse_LatestElectionId struct {
	// latest_election_id is sent as a response to a ModifyRequest that
	// includes the new_election_id field. The value is set to the latest
	// election ID that is known by the target.
	LatestElectionId *ElectionID `protobuf:"bytes,2,opt,name=latest_election_id,json=latestElectionId,proto3,oneof"`
}

func (*ModifyResponse_SessionParamsResult) isModifyResponse_Result() {}

func (*ModifyResponse_LatestElectionId) isModifyResponse_Result() {}

type OpResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *OpResult) Reset() {
	*x = OpResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_gsii_gsii_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpResult) ProtoMessage() {}

func (x *OpResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_gsii_gsii_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpResult.ProtoReflect.Descriptor instead.
func (*OpResult) Descriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{6}
}

// SessionParametersResult is used as a response from the target to the client
// to indicate that the session parameters have been accepted. If an error
// occurs, it should be reported through terminating the RPC, and populating a
// status.Status message indicating the error code and details.
type SessionParametersResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status SessionParametersResult_Status `protobuf:"varint,1,opt,name=status,proto3,enum=gsii.v1.SessionParametersResult_Status" json:"status,omitempty"`
}

func (x *SessionParametersResult) Reset() {
	*x = SessionParametersResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_proto_gsii_gsii_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SessionParametersResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionParametersResult) ProtoMessage() {}

func (x *SessionParametersResult) ProtoReflect() protoreflect.Message {
	mi := &file_v1_proto_gsii_gsii_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionParametersResult.ProtoReflect.Descriptor instead.
func (*SessionParametersResult) Descriptor() ([]byte, []int) {
	return file_v1_proto_gsii_gsii_proto_rawDescGZIP(), []int{7}
}

func (x *SessionParametersResult) GetStatus() SessionParametersResult_Status {
	if x != nil {
		return x.Status
	}
	return SessionParametersResult_INVALID
}

var File_v1_proto_gsii_gsii_proto protoreflect.FileDescriptor

var file_v1_proto_gsii_gsii_proto_rawDesc = []byte{
	0x0a, 0x18, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x73, 0x69, 0x69, 0x2f,
	0x67, 0x73, 0x69, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x67, 0x73, 0x69, 0x69,
	0x2e, 0x76, 0x31, 0x1a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x6e, 0x6d, 0x69, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6e, 0x6d, 0x69, 0x2f, 0x67, 0x6e, 0x6d, 0x69, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa1, 0x01, 0x0a, 0x0d, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x73, 0x52, 0x06, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x38, 0x0a, 0x0f, 0x6e,
	0x65, 0x77, 0x5f, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x69, 0x6e, 0x74, 0x31, 0x32, 0x38, 0x52, 0x0d, 0x6e, 0x65, 0x77, 0x45, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x02, 0x6f, 0x70, 0x22, 0x2f, 0x0a, 0x07, 0x55, 0x69, 0x6e,
	0x74, 0x31, 0x32, 0x38, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x69, 0x67, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x04, 0x68, 0x69, 0x67, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x6f, 0x77, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6c, 0x6f, 0x77, 0x22, 0xe0, 0x03, 0x0a, 0x11, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73,
	0x12, 0x4c, 0x0a, 0x0b, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a, 0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x73, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x4d, 0x6f, 0x64,
	0x65, 0x52, 0x0b, 0x70, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x4b,
	0x0a, 0x0a, 0x72, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x2b, 0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x2e, 0x43,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79, 0x52,
	0x0a, 0x72, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x42, 0x0a, 0x13, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x65, 0x6c, 0x65, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67,
	0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x69, 0x6e, 0x74, 0x31, 0x32, 0x38, 0x48, 0x00,
	0x52, 0x11, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x64, 0x12, 0x2f, 0x0a, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31,
	0x2e, 0x55, 0x69, 0x6e, 0x74, 0x31, 0x32, 0x38, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x49, 0x64, 0x22, 0x44, 0x0a, 0x0f, 0x50, 0x65, 0x72, 0x73, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x63, 0x65, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x13, 0x49, 0x4e, 0x56, 0x41, 0x4c,
	0x49, 0x44, 0x5f, 0x50, 0x45, 0x52, 0x53, 0x49, 0x53, 0x54, 0x45, 0x4e, 0x43, 0x45, 0x10, 0x00,
	0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x50, 0x52, 0x45, 0x53, 0x45, 0x52, 0x56, 0x45, 0x10, 0x02, 0x22, 0x4f, 0x0a, 0x10, 0x43, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x64, 0x75, 0x6e, 0x64, 0x61, 0x6e, 0x63, 0x79, 0x12, 0x16,
	0x0a, 0x12, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x5f, 0x52, 0x45, 0x44, 0x55, 0x4e, 0x44,
	0x41, 0x4e, 0x43, 0x59, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x4c, 0x4c, 0x5f, 0x50, 0x52,
	0x49, 0x4d, 0x41, 0x52, 0x59, 0x10, 0x01, 0x12, 0x12, 0x0a, 0x0e, 0x53, 0x49, 0x4e, 0x47, 0x4c,
	0x45, 0x5f, 0x50, 0x52, 0x49, 0x4d, 0x41, 0x52, 0x59, 0x10, 0x02, 0x42, 0x10, 0x0a, 0x0e, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0x53, 0x0a,
	0x0a, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x31, 0x0a, 0x0b, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x55,
	0x69, 0x6e, 0x74, 0x31, 0x32, 0x38, 0x52, 0x0a, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0xb8, 0x01, 0x0a, 0x09, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x30, 0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x20, 0x2e, 0x67,
	0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02,
	0x6f, 0x70, 0x12, 0x1e, 0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x0a, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x2e, 0x50, 0x61, 0x74, 0x68, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x67, 0x6e, 0x6d, 0x69, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x64, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x31, 0x0a, 0x0d, 0x4f, 0x70,
	0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49,
	0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x41, 0x44, 0x44, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x02, 0x22, 0xe4, 0x01,
	0x0a, 0x0e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x56, 0x0a, 0x15, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x70, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x20, 0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x48, 0x00, 0x52, 0x13, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x43, 0x0a, 0x12, 0x6c, 0x61, 0x74, 0x65,
	0x73, 0x74, 0x5f, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x45,
	0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x48, 0x00, 0x52, 0x10, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x45, 0x6c, 0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x2b, 0x0a,
	0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x42, 0x08, 0x0a, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0x0a, 0x0a, 0x08, 0x4f, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x79, 0x0a, 0x17, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x3f, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x27, 0x2e, 0x67, 0x73,
	0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x50, 0x61, 0x72,
	0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x1d, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49,
	0x44, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0x01, 0x32, 0x45, 0x0a, 0x04, 0x67,
	0x53, 0x49, 0x49, 0x12, 0x3d, 0x0a, 0x06, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x12, 0x16, 0x2e,
	0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x67, 0x73, 0x69, 0x69, 0x2e, 0x76, 0x31, 0x2e,
	0x4d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01,
	0x30, 0x01, 0x42, 0x2f, 0x5a, 0x2d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x70, 0x65, 0x6e, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2f, 0x67, 0x73, 0x69, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x73, 0x69, 0x69, 0x3b, 0x67,
	0x73, 0x69, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_proto_gsii_gsii_proto_rawDescOnce sync.Once
	file_v1_proto_gsii_gsii_proto_rawDescData = file_v1_proto_gsii_gsii_proto_rawDesc
)

func file_v1_proto_gsii_gsii_proto_rawDescGZIP() []byte {
	file_v1_proto_gsii_gsii_proto_rawDescOnce.Do(func() {
		file_v1_proto_gsii_gsii_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_proto_gsii_gsii_proto_rawDescData)
	})
	return file_v1_proto_gsii_gsii_proto_rawDescData
}

var file_v1_proto_gsii_gsii_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_v1_proto_gsii_gsii_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_v1_proto_gsii_gsii_proto_goTypes = []any{
	(SessionParameters_PersistenceMode)(0),  // 0: gsii.v1.SessionParameters.PersistenceMode
	(SessionParameters_ClientRedundancy)(0), // 1: gsii.v1.SessionParameters.ClientRedundancy
	(Operation_OperationType)(0),            // 2: gsii.v1.Operation.OperationType
	(SessionParametersResult_Status)(0),     // 3: gsii.v1.SessionParametersResult.Status
	(*ModifyRequest)(nil),                   // 4: gsii.v1.ModifyRequest
	(*Uint128)(nil),                         // 5: gsii.v1.Uint128
	(*SessionParameters)(nil),               // 6: gsii.v1.SessionParameters
	(*ElectionID)(nil),                      // 7: gsii.v1.ElectionID
	(*Operation)(nil),                       // 8: gsii.v1.Operation
	(*ModifyResponse)(nil),                  // 9: gsii.v1.ModifyResponse
	(*OpResult)(nil),                        // 10: gsii.v1.OpResult
	(*SessionParametersResult)(nil),         // 11: gsii.v1.SessionParametersResult
	(*gnmi.Path)(nil),                       // 12: gnmi.Path
	(*gnmi.TypedValue)(nil),                 // 13: gnmi.TypedValue
}
var file_v1_proto_gsii_gsii_proto_depIdxs = []int32{
	6,  // 0: gsii.v1.ModifyRequest.params:type_name -> gsii.v1.SessionParameters
	5,  // 1: gsii.v1.ModifyRequest.new_election_id:type_name -> gsii.v1.Uint128
	8,  // 2: gsii.v1.ModifyRequest.op:type_name -> gsii.v1.Operation
	0,  // 3: gsii.v1.SessionParameters.persistence:type_name -> gsii.v1.SessionParameters.PersistenceMode
	1,  // 4: gsii.v1.SessionParameters.redundancy:type_name -> gsii.v1.SessionParameters.ClientRedundancy
	5,  // 5: gsii.v1.SessionParameters.initial_election_id:type_name -> gsii.v1.Uint128
	5,  // 6: gsii.v1.SessionParameters.client_id:type_name -> gsii.v1.Uint128
	5,  // 7: gsii.v1.ElectionID.election_id:type_name -> gsii.v1.Uint128
	2,  // 8: gsii.v1.Operation.op:type_name -> gsii.v1.Operation.OperationType
	12, // 9: gsii.v1.Operation.path:type_name -> gnmi.Path
	13, // 10: gsii.v1.Operation.value:type_name -> gnmi.TypedValue
	11, // 11: gsii.v1.ModifyResponse.session_params_result:type_name -> gsii.v1.SessionParametersResult
	7,  // 12: gsii.v1.ModifyResponse.latest_election_id:type_name -> gsii.v1.ElectionID
	10, // 13: gsii.v1.ModifyResponse.results:type_name -> gsii.v1.OpResult
	3,  // 14: gsii.v1.SessionParametersResult.status:type_name -> gsii.v1.SessionParametersResult.Status
	4,  // 15: gsii.v1.gSII.Modify:input_type -> gsii.v1.ModifyRequest
	9,  // 16: gsii.v1.gSII.Modify:output_type -> gsii.v1.ModifyResponse
	16, // [16:17] is the sub-list for method output_type
	15, // [15:16] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_v1_proto_gsii_gsii_proto_init() }
func file_v1_proto_gsii_gsii_proto_init() {
	if File_v1_proto_gsii_gsii_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_proto_gsii_gsii_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*ModifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_gsii_gsii_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*Uint128); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_gsii_gsii_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*SessionParameters); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_gsii_gsii_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*ElectionID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_gsii_gsii_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*Operation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_gsii_gsii_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*ModifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_gsii_gsii_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*OpResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_proto_gsii_gsii_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*SessionParametersResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_proto_gsii_gsii_proto_msgTypes[2].OneofWrappers = []any{
		(*SessionParameters_InitialElectionId)(nil),
		(*SessionParameters_ClientId)(nil),
	}
	file_v1_proto_gsii_gsii_proto_msgTypes[5].OneofWrappers = []any{
		(*ModifyResponse_SessionParamsResult)(nil),
		(*ModifyResponse_LatestElectionId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_proto_gsii_gsii_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_proto_gsii_gsii_proto_goTypes,
		DependencyIndexes: file_v1_proto_gsii_gsii_proto_depIdxs,
		EnumInfos:         file_v1_proto_gsii_gsii_proto_enumTypes,
		MessageInfos:      file_v1_proto_gsii_gsii_proto_msgTypes,
	}.Build()
	File_v1_proto_gsii_gsii_proto = out.File
	file_v1_proto_gsii_gsii_proto_rawDesc = nil
	file_v1_proto_gsii_gsii_proto_goTypes = nil
	file_v1_proto_gsii_gsii_proto_depIdxs = nil
}
